// GENERATED by packages/ontology/tools/export_library.py from abox/library/crops.ttl. Do not edit.
import type { LibraryCrop } from "./library.js";

export const LIBRARY: LibraryCrop[] = [
  {
    "id": "crop-apple",
    "names": {
      "de": "Apfel",
      "en": "Apple",
      "fr": "Pommier (pomme)",
      "la": "Malus domestica"
    },
    "lifeCycle": "Perennial",
    "growthForm": "Tree",
    "parts": [
      "Fruit"
    ],
    "needs": {},
    "windows": [
      {
        "activity": "Flowering",
        "from": 4,
        "to": 5
      },
      {
        "activity": "Harvest",
        "from": 8,
        "to": 10,
        "part": "Fruit"
      },
      {
        "activity": "SummerPrune",
        "from": 7,
        "to": 8
      },
      {
        "activity": "WinterPrune",
        "from": 12,
        "to": 2
      }
    ]
  },
  {
    "id": "crop-aubergine",
    "names": {
      "de": "Aubergine",
      "en": "Aubergine",
      "fr": "Aubergine",
      "la": "Solanum melongena"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {
      "sowMinTempC": 20.0,
      "plantOutMinNightC": 13.0,
      "frostTender": true,
      "daysToHarvest": 150,
      "spacingCm": 50,
      "sowingDepthMm": 5,
      "seedsPerPoint": 2,
      "germinationDays": 12,
      "waterMmPerWeek": 30.0
    },
    "windows": [],
    "mix": {
      "family": "Solanaceae",
      "feeding": "HeavyFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 80,
      "gives": [],
      "good": [
        "crop-basil",
        "crop-bush-bean",
        "crop-thyme"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-basil",
    "names": {
      "de": "Basilikum",
      "en": "Basil",
      "fr": "Basilic",
      "la": "Ocimum basilicum"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 16.0,
      "plantOutMinNightC": 12.0,
      "frostTender": true,
      "daysToHarvest": 70,
      "spacingCm": 20,
      "sowingDepthMm": 3,
      "seedsPerPoint": 3,
      "germinationDays": 8,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Lamiaceae",
      "feeding": "MediumFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 40,
      "gives": [
        "ConfusesPests",
        "FeedsPollinators"
      ],
      "good": [
        "crop-aubergine",
        "crop-sweet-pepper",
        "crop-tomato"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-bay-laurel",
    "names": {
      "de": "Echter Lorbeer",
      "en": "Bay laurel",
      "fr": "Laurier-sauce",
      "la": "Laurus nobilis"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {},
    "windows": []
  },
  {
    "id": "crop-black-pepper",
    "names": {
      "de": "Schwarzer Pfeffer",
      "en": "Black pepper",
      "fr": "Poivre noir",
      "la": "Piper nigrum"
    },
    "lifeCycle": null,
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {},
    "windows": []
  },
  {
    "id": "crop-bush-bean",
    "names": {
      "de": "Buschbohne",
      "en": "Bush bean",
      "fr": "Haricot nain",
      "la": "Phaseolus vulgaris"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {
      "sowMinTempC": 12.0,
      "plantOutMinNightC": 8.0,
      "frostTender": true,
      "daysToHarvest": 60,
      "spacingCm": 15,
      "sowingDepthMm": 30,
      "seedsPerPoint": 2,
      "germinationDays": 8,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Fabaceae",
      "feeding": "SoilBuilder",
      "rootDepth": "MediumRoot",
      "heightCm": 45,
      "gives": [
        "FixesNitrogen"
      ],
      "good": [
        "crop-aubergine",
        "crop-courgette",
        "crop-cucumber",
        "crop-lettuce",
        "crop-radish",
        "crop-rocket",
        "crop-rosemary",
        "crop-spinach",
        "crop-swiss-chard"
      ],
      "bad": [
        "crop-chives",
        "crop-garlic",
        "crop-onion",
        "crop-spring-onion"
      ]
    }
  },
  {
    "id": "crop-caraway",
    "names": {
      "de": "Kümmel",
      "en": "Caraway",
      "fr": "Carvi",
      "la": "Carum carvi"
    },
    "lifeCycle": "Biennial",
    "growthForm": null,
    "parts": [
      "Seed"
    ],
    "needs": {
      "sowMinTempC": 8.0,
      "frostTender": false,
      "daysToHarvest": 400,
      "spacingCm": 20,
      "sowingDepthMm": 10,
      "seedsPerPoint": 3,
      "germinationDays": 14,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Apiaceae",
      "feeding": "LightFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 60,
      "gives": [
        "FeedsPollinators",
        "LoosensSoil"
      ],
      "good": [],
      "bad": [
        "crop-dill"
      ]
    }
  },
  {
    "id": "crop-carrot",
    "names": {
      "de": "Möhre",
      "en": "Carrot",
      "fr": "Carotte",
      "la": "Daucus carota"
    },
    "lifeCycle": "Biennial",
    "growthForm": null,
    "parts": [
      "Root"
    ],
    "needs": {
      "sowMinTempC": 7.0,
      "frostTender": false,
      "daysToHarvest": 75,
      "spacingCm": 5,
      "sowingDepthMm": 10,
      "seedsPerPoint": 3,
      "germinationDays": 14,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Apiaceae",
      "feeding": "LightFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 30,
      "gives": [
        "LoosensSoil"
      ],
      "good": [
        "crop-chives",
        "crop-garlic",
        "crop-lettuce",
        "crop-onion",
        "crop-radish",
        "crop-rosemary",
        "crop-spring-onion",
        "crop-sweet-pepper",
        "crop-tomato"
      ],
      "bad": [
        "crop-dill"
      ]
    }
  },
  {
    "id": "crop-chives",
    "names": {
      "de": "Schnittlauch",
      "en": "Chives",
      "fr": "Ciboulette",
      "la": "Allium schoenoprasum"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 10.0,
      "frostTender": false,
      "daysToHarvest": 90,
      "spacingCm": 20,
      "sowingDepthMm": 10,
      "seedsPerPoint": 4,
      "germinationDays": 14,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Amaryllidaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 30,
      "gives": [
        "ConfusesPests",
        "FeedsPollinators"
      ],
      "good": [
        "crop-carrot",
        "crop-lettuce",
        "crop-parsley",
        "crop-tomato"
      ],
      "bad": [
        "crop-bush-bean"
      ]
    }
  },
  {
    "id": "crop-courgette",
    "names": {
      "de": "Zucchini",
      "en": "Courgette",
      "fr": "Courgette",
      "la": "Cucurbita pepo"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {
      "sowMinTempC": 14.0,
      "plantOutMinNightC": 10.0,
      "frostTender": true,
      "daysToHarvest": 60,
      "spacingCm": 80,
      "sowingDepthMm": 25,
      "seedsPerPoint": 2,
      "germinationDays": 7,
      "waterMmPerWeek": 30.0
    },
    "windows": [],
    "mix": {
      "family": "Cucurbitaceae",
      "feeding": "HeavyFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 60,
      "gives": [
        "CoversSoil"
      ],
      "good": [
        "crop-bush-bean",
        "crop-marigold",
        "crop-onion"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-cucumber",
    "names": {
      "de": "Gurke",
      "en": "Cucumber",
      "fr": "Concombre",
      "la": "Cucumis sativus"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {
      "sowMinTempC": 15.0,
      "plantOutMinNightC": 10.0,
      "frostTender": true,
      "daysToHarvest": 60,
      "spacingCm": 40,
      "sowingDepthMm": 20,
      "seedsPerPoint": 2,
      "germinationDays": 7,
      "waterMmPerWeek": 35.0
    },
    "windows": [],
    "mix": {
      "family": "Cucurbitaceae",
      "feeding": "HeavyFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 40,
      "gives": [
        "CoversSoil"
      ],
      "good": [
        "crop-bush-bean",
        "crop-dill",
        "crop-lettuce",
        "crop-marigold",
        "crop-radish"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-dill",
    "names": {
      "de": "Dill",
      "en": "Dill",
      "fr": "Aneth",
      "la": "Anethum graveolens"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Leaf",
      "Seed"
    ],
    "needs": {
      "sowMinTempC": 10.0,
      "boltAboveC": 27.0,
      "frostTender": false,
      "daysToHarvest": 50,
      "spacingCm": 20,
      "sowingDepthMm": 10,
      "seedsPerPoint": 3,
      "germinationDays": 14,
      "waterMmPerWeek": 15.0
    },
    "windows": [],
    "mix": {
      "family": "Apiaceae",
      "feeding": "LightFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 90,
      "gives": [
        "FeedsPollinators"
      ],
      "good": [
        "crop-cucumber",
        "crop-lettuce",
        "crop-white-cabbage"
      ],
      "bad": [
        "crop-caraway",
        "crop-carrot"
      ]
    }
  },
  {
    "id": "crop-garlic",
    "names": {
      "de": "Knoblauch",
      "en": "Garlic",
      "fr": "Ail",
      "la": "Allium sativum"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Bulb"
    ],
    "needs": {
      "sowMinTempC": 5.0,
      "frostTender": false,
      "daysToHarvest": 240,
      "spacingCm": 12,
      "sowingDepthMm": 40,
      "seedsPerPoint": 1,
      "germinationDays": 14,
      "waterMmPerWeek": 15.0
    },
    "windows": [],
    "mix": {
      "family": "Amaryllidaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 50,
      "gives": [
        "ConfusesPests"
      ],
      "good": [
        "crop-carrot",
        "crop-lettuce",
        "crop-swiss-chard",
        "crop-tomato"
      ],
      "bad": [
        "crop-bush-bean"
      ]
    }
  },
  {
    "id": "crop-lettuce",
    "names": {
      "de": "Salat",
      "en": "Lettuce",
      "fr": "Laitue",
      "la": "Lactuca sativa"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 5.0,
      "boltAboveC": 25.0,
      "frostTender": false,
      "daysToHarvest": 55,
      "spacingCm": 25,
      "sowingDepthMm": 5,
      "seedsPerPoint": 3,
      "germinationDays": 7,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Asteraceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 25,
      "gives": [],
      "good": [
        "crop-bush-bean",
        "crop-carrot",
        "crop-chives",
        "crop-cucumber",
        "crop-dill",
        "crop-garlic",
        "crop-onion",
        "crop-radish",
        "crop-rocket",
        "crop-spinach",
        "crop-spring-onion",
        "crop-tomato"
      ],
      "bad": [
        "crop-parsley"
      ]
    }
  },
  {
    "id": "crop-marigold",
    "names": {
      "de": "Studentenblume",
      "en": "French marigold",
      "fr": "Œillet d'Inde",
      "la": "Tagetes patula"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Flower"
    ],
    "needs": {
      "sowMinTempC": 12.0,
      "plantOutMinNightC": 8.0,
      "frostTender": true,
      "daysToHarvest": 60,
      "spacingCm": 20,
      "sowingDepthMm": 5,
      "seedsPerPoint": 2,
      "germinationDays": 7,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Asteraceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 30,
      "gives": [
        "ConfusesPests",
        "FeedsPollinators"
      ],
      "good": [
        "crop-courgette",
        "crop-cucumber",
        "crop-sweet-pepper",
        "crop-tomato",
        "crop-white-cabbage"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-onion",
    "names": {
      "de": "Zwiebel",
      "en": "Onion",
      "fr": "Oignon",
      "la": "Allium cepa"
    },
    "lifeCycle": "Biennial",
    "growthForm": null,
    "parts": [
      "Bulb"
    ],
    "needs": {
      "sowMinTempC": 7.0,
      "frostTender": false,
      "daysToHarvest": 120,
      "spacingCm": 10,
      "sowingDepthMm": 10,
      "seedsPerPoint": 1,
      "germinationDays": 12,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Amaryllidaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 40,
      "gives": [
        "ConfusesPests"
      ],
      "good": [
        "crop-carrot",
        "crop-courgette",
        "crop-lettuce",
        "crop-sweet-pepper",
        "crop-swiss-chard",
        "crop-tomato",
        "crop-white-cabbage"
      ],
      "bad": [
        "crop-bush-bean"
      ]
    }
  },
  {
    "id": "crop-parsley",
    "names": {
      "de": "Petersilie",
      "en": "Parsley",
      "fr": "Persil",
      "la": "Petroselinum crispum"
    },
    "lifeCycle": "Biennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 8.0,
      "frostTender": false,
      "daysToHarvest": 75,
      "spacingCm": 15,
      "sowingDepthMm": 10,
      "seedsPerPoint": 3,
      "germinationDays": 21,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Apiaceae",
      "feeding": "MediumFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 30,
      "gives": [
        "FeedsPollinators"
      ],
      "good": [
        "crop-chives",
        "crop-radish",
        "crop-tomato"
      ],
      "bad": [
        "crop-lettuce"
      ]
    }
  },
  {
    "id": "crop-pear",
    "names": {
      "de": "Birne",
      "en": "Pear",
      "fr": "Poirier (poire)",
      "la": "Pyrus communis"
    },
    "lifeCycle": "Perennial",
    "growthForm": "Tree",
    "parts": [
      "Fruit"
    ],
    "needs": {},
    "windows": [
      {
        "activity": "Flowering",
        "from": 4,
        "to": 4
      },
      {
        "activity": "Harvest",
        "from": 8,
        "to": 10,
        "part": "Fruit"
      },
      {
        "activity": "SummerPrune",
        "from": 7,
        "to": 8
      },
      {
        "activity": "WinterPrune",
        "from": 12,
        "to": 2
      }
    ]
  },
  {
    "id": "crop-phacelia",
    "names": {
      "de": "Phacelia",
      "en": "Phacelia",
      "fr": "Phacélie",
      "la": "Phacelia tanacetifolia"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Flower"
    ],
    "needs": {
      "sowMinTempC": 8.0,
      "frostTender": true,
      "daysToHarvest": 50,
      "spacingCm": 10,
      "sowingDepthMm": 10,
      "seedsPerPoint": 4,
      "germinationDays": 10,
      "waterMmPerWeek": 15.0
    },
    "windows": [],
    "mix": {
      "family": "Hydrophyllaceae",
      "feeding": "LightFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 60,
      "gives": [
        "CoversSoil",
        "FeedsPollinators",
        "LoosensSoil"
      ],
      "good": [],
      "bad": []
    },
    "coverCrop": true
  },
  {
    "id": "crop-plum",
    "names": {
      "de": "Pflaume",
      "en": "Plum",
      "fr": "Prunier (prune)",
      "la": "Prunus domestica"
    },
    "lifeCycle": "Perennial",
    "growthForm": "Tree",
    "parts": [
      "Fruit"
    ],
    "needs": {},
    "windows": [
      {
        "activity": "Flowering",
        "from": 3,
        "to": 4
      },
      {
        "activity": "Harvest",
        "from": 8,
        "to": 9,
        "part": "Fruit"
      },
      {
        "activity": "SummerPrune",
        "from": 6,
        "to": 7
      }
    ]
  },
  {
    "id": "crop-radish",
    "names": {
      "de": "Radieschen",
      "en": "Radish",
      "fr": "Radis",
      "la": "Raphanus sativus"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Root"
    ],
    "needs": {
      "sowMinTempC": 5.0,
      "boltAboveC": 24.0,
      "frostTender": false,
      "daysToHarvest": 30,
      "spacingCm": 5,
      "sowingDepthMm": 10,
      "seedsPerPoint": 2,
      "germinationDays": 5,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Brassicaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 15,
      "gives": [
        "LoosensSoil"
      ],
      "good": [
        "crop-bush-bean",
        "crop-carrot",
        "crop-cucumber",
        "crop-lettuce",
        "crop-parsley",
        "crop-spinach"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-rocket",
    "names": {
      "de": "Rucola",
      "en": "Rocket",
      "fr": "Roquette",
      "la": "Eruca vesicaria"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 5.0,
      "boltAboveC": 24.0,
      "frostTender": false,
      "daysToHarvest": 35,
      "spacingCm": 10,
      "sowingDepthMm": 5,
      "seedsPerPoint": 3,
      "germinationDays": 6,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Brassicaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 25,
      "gives": [],
      "good": [
        "crop-bush-bean",
        "crop-lettuce"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-rosemary",
    "names": {
      "de": "Rosmarin",
      "en": "Rosemary",
      "fr": "Romarin",
      "la": "Salvia rosmarinus"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 15.0,
      "frostTender": false,
      "daysToHarvest": 365,
      "spacingCm": 60,
      "sowingDepthMm": 2,
      "seedsPerPoint": 3,
      "germinationDays": 21,
      "waterMmPerWeek": 10.0
    },
    "windows": [],
    "mix": {
      "family": "Lamiaceae",
      "feeding": "LightFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 100,
      "gives": [
        "ConfusesPests",
        "FeedsPollinators"
      ],
      "good": [
        "crop-bush-bean",
        "crop-carrot",
        "crop-white-cabbage"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-sour-cherry",
    "names": {
      "de": "Sauerkirsche",
      "en": "Sour cherry",
      "fr": "Cerisier acide (griotte)",
      "la": "Prunus cerasus"
    },
    "lifeCycle": "Perennial",
    "growthForm": "Tree",
    "parts": [
      "Fruit"
    ],
    "needs": {},
    "windows": [
      {
        "activity": "Flowering",
        "from": 4,
        "to": 5
      },
      {
        "activity": "Harvest",
        "from": 7,
        "to": 8,
        "part": "Fruit"
      },
      {
        "activity": "SummerPrune",
        "from": 8,
        "to": 8
      }
    ]
  },
  {
    "id": "crop-spinach",
    "names": {
      "de": "Spinat",
      "en": "Spinach",
      "fr": "Épinard",
      "la": "Spinacia oleracea"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 4.0,
      "boltAboveC": 22.0,
      "frostTender": false,
      "daysToHarvest": 45,
      "spacingCm": 10,
      "sowingDepthMm": 20,
      "seedsPerPoint": 2,
      "germinationDays": 10,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Amaranthaceae",
      "feeding": "MediumFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 25,
      "gives": [],
      "good": [
        "crop-bush-bean",
        "crop-lettuce",
        "crop-radish",
        "crop-white-cabbage"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-spring-onion",
    "names": {
      "de": "Frühlingszwiebel",
      "en": "Spring onion",
      "fr": "Ciboule",
      "la": "Allium fistulosum"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 7.0,
      "frostTender": false,
      "daysToHarvest": 70,
      "spacingCm": 5,
      "sowingDepthMm": 10,
      "seedsPerPoint": 3,
      "germinationDays": 12,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Amaryllidaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 35,
      "gives": [
        "ConfusesPests"
      ],
      "good": [
        "crop-carrot",
        "crop-lettuce"
      ],
      "bad": [
        "crop-bush-bean"
      ]
    }
  },
  {
    "id": "crop-sweet-cherry",
    "names": {
      "de": "Süßkirsche",
      "en": "Sweet cherry",
      "fr": "Cerisier (cerise douce)",
      "la": "Prunus avium"
    },
    "lifeCycle": "Perennial",
    "growthForm": "Tree",
    "parts": [
      "Fruit"
    ],
    "needs": {},
    "windows": [
      {
        "activity": "Flowering",
        "from": 4,
        "to": 4
      },
      {
        "activity": "Harvest",
        "from": 6,
        "to": 7,
        "part": "Fruit"
      },
      {
        "activity": "SummerPrune",
        "from": 7,
        "to": 8
      }
    ]
  },
  {
    "id": "crop-sweet-pepper",
    "names": {
      "de": "Paprika",
      "en": "Sweet pepper",
      "fr": "Poivron",
      "la": "Capsicum annuum"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {
      "sowMinTempC": 18.0,
      "plantOutMinNightC": 12.0,
      "frostTender": true,
      "daysToHarvest": 150,
      "spacingCm": 40,
      "sowingDepthMm": 5,
      "seedsPerPoint": 2,
      "germinationDays": 12,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Solanaceae",
      "feeding": "HeavyFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 70,
      "gives": [],
      "good": [
        "crop-basil",
        "crop-carrot",
        "crop-marigold",
        "crop-onion"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-swiss-chard",
    "names": {
      "de": "Mangold",
      "en": "Swiss chard",
      "fr": "Blette (poirée)",
      "la": "Beta vulgaris"
    },
    "lifeCycle": "Biennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 8.0,
      "frostTender": false,
      "daysToHarvest": 60,
      "spacingCm": 30,
      "sowingDepthMm": 20,
      "seedsPerPoint": 1,
      "germinationDays": 10,
      "waterMmPerWeek": 25.0
    },
    "windows": [],
    "mix": {
      "family": "Amaranthaceae",
      "feeding": "MediumFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 50,
      "gives": [],
      "good": [
        "crop-bush-bean",
        "crop-garlic",
        "crop-onion",
        "crop-white-cabbage"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-thyme",
    "names": {
      "de": "Thymian",
      "en": "Thyme",
      "fr": "Thym",
      "la": "Thymus vulgaris"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 13.0,
      "frostTender": false,
      "daysToHarvest": 120,
      "spacingCm": 25,
      "sowingDepthMm": 1,
      "seedsPerPoint": 4,
      "germinationDays": 14,
      "waterMmPerWeek": 10.0
    },
    "windows": [],
    "mix": {
      "family": "Lamiaceae",
      "feeding": "LightFeeder",
      "rootDepth": "ShallowRoot",
      "heightCm": 25,
      "gives": [
        "ConfusesPests",
        "CoversSoil",
        "FeedsPollinators"
      ],
      "good": [
        "crop-aubergine",
        "crop-tomato",
        "crop-white-cabbage"
      ],
      "bad": []
    }
  },
  {
    "id": "crop-tomato",
    "names": {
      "de": "Tomate",
      "en": "Tomato",
      "fr": "Tomate",
      "la": "Solanum lycopersicum"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Fruit"
    ],
    "needs": {
      "sowMinTempC": 16.0,
      "plantOutMinNightC": 10.0,
      "frostTender": true,
      "daysToHarvest": 120,
      "spacingCm": 50,
      "sowingDepthMm": 5,
      "seedsPerPoint": 2,
      "germinationDays": 8,
      "waterMmPerWeek": 30.0
    },
    "windows": [],
    "mix": {
      "family": "Solanaceae",
      "feeding": "HeavyFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 150,
      "gives": [],
      "good": [
        "crop-basil",
        "crop-carrot",
        "crop-chives",
        "crop-garlic",
        "crop-lettuce",
        "crop-marigold",
        "crop-onion",
        "crop-parsley",
        "crop-thyme"
      ],
      "bad": [
        "crop-white-cabbage"
      ]
    }
  },
  {
    "id": "crop-walnut",
    "names": {
      "de": "Walnuss",
      "en": "Walnut",
      "fr": "Noyer (noix)",
      "la": "Juglans regia"
    },
    "lifeCycle": "Perennial",
    "growthForm": "Tree",
    "parts": [
      "Fruit",
      "Seed"
    ],
    "needs": {},
    "windows": [
      {
        "activity": "Flowering",
        "from": 4,
        "to": 5
      },
      {
        "activity": "Harvest",
        "from": 9,
        "to": 10,
        "part": "Seed"
      },
      {
        "activity": "SummerPrune",
        "from": 8,
        "to": 9
      }
    ]
  },
  {
    "id": "crop-white-cabbage",
    "names": {
      "de": "Weißkohl",
      "en": "White cabbage",
      "fr": "Chou blanc",
      "la": "Brassica oleracea"
    },
    "lifeCycle": "Biennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 7.0,
      "frostTender": false,
      "daysToHarvest": 120,
      "spacingCm": 50,
      "sowingDepthMm": 10,
      "seedsPerPoint": 2,
      "germinationDays": 7,
      "waterMmPerWeek": 30.0
    },
    "windows": [],
    "mix": {
      "family": "Brassicaceae",
      "feeding": "HeavyFeeder",
      "rootDepth": "MediumRoot",
      "heightCm": 40,
      "gives": [],
      "good": [
        "crop-dill",
        "crop-marigold",
        "crop-onion",
        "crop-rosemary",
        "crop-spinach",
        "crop-swiss-chard",
        "crop-thyme"
      ],
      "bad": [
        "crop-tomato"
      ]
    }
  },
  {
    "id": "crop-white-clover",
    "names": {
      "de": "Weißklee",
      "en": "White clover",
      "fr": "Trèfle blanc",
      "la": "Trifolium repens"
    },
    "lifeCycle": "Perennial",
    "growthForm": null,
    "parts": [
      "Leaf"
    ],
    "needs": {
      "sowMinTempC": 8.0,
      "frostTender": false,
      "daysToHarvest": 60,
      "spacingCm": 10,
      "sowingDepthMm": 5,
      "seedsPerPoint": 6,
      "germinationDays": 8,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Fabaceae",
      "feeding": "SoilBuilder",
      "rootDepth": "ShallowRoot",
      "heightCm": 15,
      "gives": [
        "CoversSoil",
        "FeedsPollinators",
        "FixesNitrogen"
      ],
      "good": [],
      "bad": []
    },
    "coverCrop": true
  },
  {
    "id": "crop-white-mustard",
    "names": {
      "de": "Weißer Senf",
      "en": "White mustard",
      "fr": "Moutarde blanche",
      "la": "Sinapis alba"
    },
    "lifeCycle": "Annual",
    "growthForm": null,
    "parts": [
      "Seed"
    ],
    "needs": {
      "sowMinTempC": 5.0,
      "frostTender": false,
      "daysToHarvest": 90,
      "spacingCm": 10,
      "sowingDepthMm": 10,
      "seedsPerPoint": 3,
      "germinationDays": 5,
      "waterMmPerWeek": 20.0
    },
    "windows": [],
    "mix": {
      "family": "Brassicaceae",
      "feeding": "LightFeeder",
      "rootDepth": "DeepRoot",
      "heightCm": 60,
      "gives": [
        "CoversSoil",
        "LoosensSoil"
      ],
      "good": [],
      "bad": []
    },
    "coverCrop": true
  }
];
