// GENERATED by packages/ontology/tools/export_library.py from abox/recipes/*.ttl. Do not edit.
import type { Recipe } from "./recipes.js";

export const RECIPES: Recipe[] = [
  {
    "id": "recipe-burger-aux-carottes",
    "names": {
      "de": "Burger im Möhrenbrötchen",
      "en": "Carrot-bun burger",
      "fr": "Burger aux carottes"
    },
    "yield": "2 burgers",
    "description": "The bun is made of grated carrot, egg and cheese. Carrot, chives, red onion, rocket, garlic, paprika and gherkins can come from the bed; meat, dairy, egg and lime are bought.",
    "keepsAs": null,
    "lines": [
      {
        "text": "1 cuillère à café de moutarde",
        "cropId": "crop-white-mustard",
        "part": "Seed",
        "methods": [
          "Dried"
        ]
      },
      {
        "text": "3 carottes",
        "cropId": "crop-carrot",
        "part": "Root",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "ail en poudre",
        "cropId": "crop-garlic",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Dried",
          "Fresh"
        ]
      },
      {
        "text": "ciboulette fraîche",
        "cropId": "crop-chives",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "cornichons en morceaux, et un peu de jus du pot",
        "cropId": "crop-cucumber",
        "part": "Fruit",
        "methods": [
          "Pickled"
        ]
      },
      {
        "text": "oignon rouge",
        "cropId": "crop-onion",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "paprika fumé",
        "cropId": "crop-sweet-pepper",
        "part": "Fruit",
        "methods": [
          "Dried"
        ]
      },
      {
        "text": "roquette",
        "cropId": "crop-rocket",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 œuf"
      },
      {
        "text": "2 tranches de cheddar"
      },
      {
        "text": "3 cuillères à soupe de yaourt grec"
      },
      {
        "text": "le jus d'un demi citron vert"
      },
      {
        "text": "sel et poivre"
      },
      {
        "text": "une barquette de viande hachée"
      },
      {
        "text": "une poignée de mozzarella râpée"
      }
    ],
    "steps": []
  },
  {
    "id": "recipe-choucroute",
    "names": {
      "de": "Hausgemachtes Sauerkraut",
      "en": "Home-made sauerkraut",
      "fr": "Choucroute maison"
    },
    "yield": "un bocal de 1,5 l",
    "description": "About 2 % salt by weight; keep the cabbage under its brine; cool place once fermented.",
    "keepsAs": "Fermented",
    "lines": [
      {
        "text": "1 cuillère à café de graines de carvi",
        "cropId": "crop-caraway",
        "part": "Seed",
        "methods": [
          "Dried"
        ]
      },
      {
        "text": "1 kg de chou blanc",
        "cropId": "crop-white-cabbage",
        "part": "Leaf",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "20 g de sel"
      }
    ],
    "steps": [
      "Retirer les feuilles extérieures et le trognon, émincer le chou très finement.",
      "Mélanger avec le sel et le carvi, malaxer jusqu'à ce que le chou rende son jus.",
      "Tasser fortement dans un bocal ou un pot à choucroute, le chou doit être couvert de son jus ; poser un poids.",
      "Laisser fermenter 3 à 4 semaines vers 18 à 20 °C, puis conserver au frais."
    ]
  },
  {
    "id": "recipe-clafoutis-aux-cerises",
    "names": {
      "de": "Kirsch-Clafoutis",
      "en": "Cherry clafoutis",
      "fr": "Clafoutis aux cerises"
    },
    "yield": "6 parts",
    "description": "Traditionally with unstoned cherries; sour cherries work with a little more sugar. Frozen cherries go in still frozen.",
    "keepsAs": null,
    "lines": [
      {
        "text": "500 g de cerises",
        "cropId": "crop-sweet-cherry",
        "part": "Fruit",
        "methods": [
          "Fresh",
          "Frozen"
        ]
      },
      {
        "text": "3 œufs"
      },
      {
        "text": "30 cl de lait"
      },
      {
        "text": "30 g de beurre"
      },
      {
        "text": "80 g de farine"
      },
      {
        "text": "80 g de sucre"
      }
    ],
    "steps": [
      "Beurrer un plat et y répartir les cerises.",
      "Battre les œufs avec le sucre, ajouter la farine, puis le lait et le beurre fondu.",
      "Verser sur les cerises et cuire 35 à 40 minutes à 180 °C."
    ]
  },
  {
    "id": "recipe-compote-de-pommes",
    "names": {
      "de": "Apfelkompott im Glas",
      "en": "Bottled apple compote",
      "fr": "Compote de pommes en bocaux"
    },
    "yield": "environ 4 bocaux de 500 ml",
    "description": "Apples are acid enough for bottling at 100 °C; follow the jar maker's time.",
    "keepsAs": "Bottled",
    "lines": [
      {
        "text": "2 kg de pommes",
        "cropId": "crop-apple",
        "part": "Fruit",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "1 bâton de cannelle"
      },
      {
        "text": "10 cl d'eau"
      },
      {
        "text": "100 g de sucre (facultatif)"
      }
    ],
    "steps": [
      "Éplucher, épépiner et couper les pommes en morceaux.",
      "Les cuire à couvert avec l'eau et la cannelle 15 à 20 minutes, sucrer à son goût.",
      "Écraser ou laisser en morceaux, remplir les bocaux chauds.",
      "Fermer et stériliser selon la notice du fabricant de bocaux."
    ]
  },
  {
    "id": "recipe-confiture-de-prunes",
    "names": {
      "de": "Pflaumenmarmelade",
      "en": "Plum jam",
      "fr": "Confiture de prunes"
    },
    "yield": "environ 5 pots de 370 g",
    "description": "Ripe plums, stoned; the jam sets at 105 °C or when a drop wrinkles on a cold plate.",
    "keepsAs": "Bottled",
    "lines": [
      {
        "text": "2 kg de prunes",
        "cropId": "crop-plum",
        "part": "Fruit",
        "methods": [
          "Fresh",
          "Frozen"
        ]
      },
      {
        "text": "1 citron"
      },
      {
        "text": "1,2 kg de sucre"
      }
    ],
    "steps": [
      "Dénoyauter les prunes et les couper en quartiers.",
      "Les laisser macérer une nuit avec le sucre et le jus de citron.",
      "Cuire à feu vif en remuant jusqu'à la prise, environ 20 minutes.",
      "Mettre en pots chauds, fermer et retourner."
    ]
  },
  {
    "id": "recipe-courgettes-marinees",
    "names": {
      "de": "Eingelegte Zucchini",
      "en": "Marinated courgettes",
      "fr": "Courgettes marinées"
    },
    "yield": "500 g de courgettes",
    "description": "",
    "keepsAs": "Pickled",
    "lines": [
      {
        "text": "1 gros oignon émincé",
        "cropId": "crop-onion",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "1 poivron coupé en morceaux",
        "cropId": "crop-sweet-pepper",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "500 g de courgettes",
        "cropId": "crop-courgette",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "de l'aneth",
        "cropId": "crop-dill",
        "part": "Leaf",
        "methods": [
          "Dried",
          "Fresh"
        ]
      },
      {
        "text": "des graines de moutarde",
        "cropId": "crop-white-mustard",
        "part": "Seed",
        "methods": [
          "Dried"
        ]
      },
      {
        "text": "du poivre",
        "cropId": "crop-black-pepper",
        "part": "Fruit",
        "methods": [
          "Dried"
        ]
      },
      {
        "text": "1 cuillère à café de sel"
      },
      {
        "text": "2 cuillères à soupe de sucre"
      },
      {
        "text": "2 cuillères à soupe de vinaigre (essence de vinaigre à 24 %)"
      },
      {
        "text": "4 cuillères à soupe d'eau"
      },
      {
        "text": "du curry"
      }
    ],
    "steps": [
      "Éplucher les courgettes, les évider et les couper en lamelles.",
      "Mélanger ensemble : 2 cuillères à soupe de vinaigre (essence de vinaigre à 24 %), 4 cuillères à soupe d'eau, 2 cuillères à soupe de sucre et 1 cuillère à café de sel.",
      "Ajouter : 1 gros oignon émincé, 1 poivron coupé en morceaux, de l'aneth, du poivre, des graines de moutarde et du curry.",
      "Laisser mariner au réfrigérateur pendant 3 jours dans un récipient couvert, et remuer le tout 3 fois par jour !"
    ]
  },
  {
    "id": "recipe-herbes-sechees",
    "names": {
      "de": "Getrocknete Gartenkräuter",
      "en": "Garden dried herbs",
      "fr": "Herbes séchées du jardin"
    },
    "yield": "un bocal",
    "description": "Pick on a dry morning before flowering; dry in the shade; store airtight and dark.",
    "keepsAs": "Dried",
    "lines": [
      {
        "text": "1 botte de romarin",
        "cropId": "crop-rosemary",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 botte de thym",
        "cropId": "crop-thyme",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "une poignée de feuilles de laurier",
        "cropId": "crop-bay-laurel",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      }
    ],
    "steps": [
      "Couper les branches de thym et de romarin et les feuilles de laurier un matin sec, avant la floraison.",
      "Les lier en petits bouquets et les suspendre à l'ombre, dans un endroit sec et aéré, 1 à 2 semaines.",
      "Effeuiller quand les feuilles se brisent sous les doigts.",
      "Conserver dans un bocal fermé, à l'abri de la lumière."
    ]
  },
  {
    "id": "recipe-pistou",
    "names": {
      "de": "Pistou (Basilikumsauce)",
      "en": "Pistou (basil sauce)",
      "fr": "Pistou"
    },
    "yield": "environ 12 portions",
    "description": "Garlic in oil must not be kept at room temperature: freeze at once. Add cheese only when serving.",
    "keepsAs": "Frozen",
    "lines": [
      {
        "text": "1 gros bouquet de basilic (50 g de feuilles)",
        "cropId": "crop-basil",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "3 gousses d'ail",
        "cropId": "crop-garlic",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "1 pincée de sel"
      },
      {
        "text": "10 cl d'huile d'olive"
      },
      {
        "text": "parmesan râpé (à l'usage)"
      }
    ],
    "steps": [
      "Laver et sécher le basilic, éplucher l'ail.",
      "Piler ou mixer le basilic et l'ail avec le sel, puis ajouter l'huile d'olive en filet.",
      "Répartir aussitôt dans un bac à glaçons et congeler ; démouler les cubes dans un sac.",
      "Au moment de servir, ajouter éventuellement du parmesan râpé."
    ]
  },
  {
    "id": "recipe-ratatouille",
    "names": {
      "de": "Ratatouille",
      "en": "Ratatouille",
      "fr": "Ratatouille"
    },
    "yield": "4 à 6 personnes, 2 à 3 boîtes de congélation",
    "description": "Frozen, not bottled: low-acid vegetables bottled at 100 °C carry a botulism risk.",
    "keepsAs": "Frozen",
    "lines": [
      {
        "text": "1 feuille de laurier",
        "cropId": "crop-bay-laurel",
        "part": "Leaf",
        "methods": [
          "Dried",
          "Fresh"
        ]
      },
      {
        "text": "2 aubergines",
        "cropId": "crop-aubergine",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "2 branches de thym",
        "cropId": "crop-thyme",
        "part": "Leaf",
        "methods": [
          "Dried",
          "Fresh"
        ]
      },
      {
        "text": "2 oignons",
        "cropId": "crop-onion",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "2 poivrons",
        "cropId": "crop-sweet-pepper",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "3 courgettes",
        "cropId": "crop-courgette",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "3 gousses d'ail",
        "cropId": "crop-garlic",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "6 tomates bien mûres",
        "cropId": "crop-tomato",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "poivre",
        "cropId": "crop-black-pepper",
        "part": "Fruit",
        "methods": [
          "Dried"
        ]
      },
      {
        "text": "quelques feuilles de basilic",
        "cropId": "crop-basil",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "6 cuillères à soupe d'huile d'olive"
      },
      {
        "text": "sel"
      }
    ],
    "steps": [
      "Couper les aubergines, les courgettes et les poivrons en dés ; émincer les oignons et l'ail.",
      "Faire revenir chaque légume séparément dans l'huile d'olive, puis les réunir avec les tomates concassées, le thym et le laurier.",
      "Saler, poivrer et laisser mijoter 45 minutes à couvert ; ajouter le basilic à la fin.",
      "Laisser refroidir, répartir en portions et congeler aussitôt."
    ]
  },
  {
    "id": "recipe-salade-du-toit",
    "names": {
      "de": "Dachbeet-Salat",
      "en": "Roof-bed salad",
      "fr": "Salade du toit"
    },
    "yield": "2 personnes",
    "description": "Whatever the bed gives that week: pick just before eating.",
    "keepsAs": null,
    "lines": [
      {
        "text": "1 ciboule",
        "cropId": "crop-spring-onion",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 cuillère de ciboulette",
        "cropId": "crop-chives",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 cuillère de persil",
        "cropId": "crop-parsley",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 poignée de jeunes épinards",
        "cropId": "crop-spinach",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 poignée de roquette",
        "cropId": "crop-rocket",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "2 poignées de laitue",
        "cropId": "crop-lettuce",
        "part": "Leaf",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "6 radis",
        "cropId": "crop-radish",
        "part": "Root",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 cuillère de vinaigre"
      },
      {
        "text": "1 cuillère à café de moutarde"
      },
      {
        "text": "3 cuillères d'huile"
      },
      {
        "text": "sel, poivre"
      }
    ],
    "steps": [
      "Cueillir les feuilles juste avant le repas, les laver et bien les essorer.",
      "Couper les radis en rondelles, ciseler la ciboulette, le persil et la ciboule.",
      "Mélanger la moutarde, le vinaigre, le sel et le poivre, puis ajouter l'huile.",
      "Assaisonner au dernier moment."
    ]
  },
  {
    "id": "recipe-sauce-tomate",
    "names": {
      "de": "Tomatensauce im Glas",
      "en": "Bottled tomato sauce",
      "fr": "Sauce tomate en bocaux"
    },
    "yield": "environ 4 bocaux de 500 ml",
    "description": "Lemon juice added for acidity before bottling; follow the jar maker's sterilisation time.",
    "keepsAs": "Bottled",
    "lines": [
      {
        "text": "2 feuilles de laurier",
        "cropId": "crop-bay-laurel",
        "part": "Leaf",
        "methods": [
          "Dried",
          "Fresh"
        ]
      },
      {
        "text": "2 oignons",
        "cropId": "crop-onion",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "3 branches de thym",
        "cropId": "crop-thyme",
        "part": "Leaf",
        "methods": [
          "Dried",
          "Fresh"
        ]
      },
      {
        "text": "3 kg de tomates",
        "cropId": "crop-tomato",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "4 gousses d'ail",
        "cropId": "crop-garlic",
        "part": "Bulb",
        "methods": [
          "Cellar",
          "Fresh"
        ]
      },
      {
        "text": "3 cuillères à soupe d'huile d'olive"
      },
      {
        "text": "4 cuillères à soupe de jus de citron"
      },
      {
        "text": "sel"
      }
    ],
    "steps": [
      "Ébouillanter et peler les tomates, les couper en morceaux.",
      "Faire revenir l'oignon et l'ail émincés dans l'huile, ajouter les tomates, le thym et le laurier ; cuire à découvert 1 heure jusqu'à épaississement. Saler.",
      "Retirer le laurier, mettre 1 cuillère à soupe de jus de citron dans chaque bocal de 500 ml, remplir de sauce chaude.",
      "Fermer et stériliser selon la notice du fabricant de bocaux ; laisser refroidir, vérifier la fermeture."
    ]
  },
  {
    "id": "recipe-vin-de-noix",
    "names": {
      "de": "Nusswein",
      "en": "Walnut wine",
      "fr": "Vin de noix"
    },
    "yield": "environ 6 litres",
    "description": "Green walnuts are picked around the Saint-Jean (late June), before the shell hardens.",
    "keepsAs": "Macerated",
    "lines": [
      {
        "text": "40 noix vertes",
        "cropId": "crop-walnut",
        "part": "Fruit",
        "methods": [
          "Fresh"
        ]
      },
      {
        "text": "1 kg de sucre"
      },
      {
        "text": "1 litre d'eau-de-vie"
      },
      {
        "text": "5 litres de vin rouge"
      }
    ],
    "steps": [
      "Cueillir les noix vertes vers la Saint-Jean, les couper en quatre (gants : elles tachent).",
      "Les mettre dans un grand récipient avec le vin rouge, l'eau-de-vie et le sucre ; remuer.",
      "Laisser macérer 40 jours au frais et à l'abri de la lumière, en remuant de temps en temps.",
      "Filtrer, mettre en bouteilles et attendre quelques mois avant de servir."
    ]
  }
];
