#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Export the crop library for the app: packages/core/src/library.generated.ts.

    packages/ontology/.venv/bin/python packages/ontology/tools/export_library.py

The site and the Lambdas do not read Turtle at run time; they get the crop
library as typed data: names (EN, FR, DE, Latin), life cycle, growth form,
what the crop needs (for the calendar) and its typical windows. crops.ttl
stays the source; tests/test_library_export.py fails when this file drifts.
"""
import json
import os

from rdflib import Graph, Namespace
from rdflib.namespace import RDF, RDFS

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LIBRARY = os.path.join(ROOT, "abox", "library", "crops.ttl")
OUT = os.path.join(ROOT, "..", "core", "src", "library.generated.ts")
PERMA = Namespace("https://permaculture.digitalhome.cloud/ontology#")
ID = "https://permaculture.digitalhome.cloud/id/"
NEEDS = ("sowMinTempC", "plantOutMinNightC", "boltAboveC", "frostTender", "daysToHarvest", "spacingCm",
         "sowingDepthMm", "seedsPerPoint", "germinationDays", "waterMmPerWeek")
INTS = ("daysToHarvest", "spacingCm", "sowingDepthMm", "seedsPerPoint", "germinationDays")


def local(node):
    return str(node).split("#")[-1] if node is not None else None


def export(g):
    crops = []
    for crop in sorted(g.subjects(RDF.type, PERMA.Crop)):
        names = {l.language: str(l) for l in g.objects(crop, RDFS.label) if l.language in ("en", "fr", "de", "la")}
        saving = g.value(crop, PERMA.seedSaving)
        needs = {}
        for n in NEEDS:
            v = g.value(crop, PERMA[n])
            if v is not None:
                v = v.toPython()
                needs[n] = v if isinstance(v, bool) else (int(v) if n in INTS else float(v))
        windows = []
        for w in g.objects(crop, PERMA.typicalWindow):
            x = {"activity": local(g.value(w, PERMA.activity)),
                 "from": int(g.value(w, PERMA.fromMonth)), "to": int(g.value(w, PERMA.toMonth))}
            if g.value(w, PERMA.part) is not None:
                x["part"] = local(g.value(w, PERMA.part))
            windows.append(x)
        windows.sort(key=lambda x: (x["activity"], x["from"]))
        crops.append({
            "id": str(crop)[len(ID):],
            "names": dict(sorted(names.items())),
            "lifeCycle": local(g.value(saving, PERMA.lifeCycle)) if saving is not None else None,
            "growthForm": local(g.value(crop, PERMA.growthForm)),
            "parts": sorted(local(g.value(y, PERMA.part)) for y in g.objects(crop, PERMA.yields)),
            "needs": needs,
            "windows": windows,
        })
    return crops


def render(crops):
    return ("// GENERATED by packages/ontology/tools/export_library.py from abox/library/crops.ttl. Do not edit.\n"
            'import type { LibraryCrop } from "./library.js";\n\n'
            f"export const LIBRARY: LibraryCrop[] = {json.dumps(crops, ensure_ascii=False, indent=2)};\n")


def main():
    text = render(export(Graph().parse(LIBRARY)))
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"-> {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
