#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Link taxa to Wikidata and TAXREF, through their GBIF ID.

    packages/ontology/.venv/bin/python packages/ontology/tools/wikidata_link.py      # writes abox/library/taxa-wikidata.ttl

Reads every dwc:Taxon with a GBIF IRI (from abox/library/crops-gbif.ttl, later
also the biodiversity register), asks the Wikidata Query Service which item has
that GBIF taxon ID (P846), and records the item, its TAXREF ID (P3186) and the
global IUCN category (P141) when present.

Why Wikidata: TAXREF's own API (taxref.mnhn.fr) answers scripts with a
bot challenge since the MNHN outage; Wikidata carries the same identifiers.
French protection and red-list statuses are not in Wikidata: they will come
from TAXREF's downloadable status file. No key needed.
"""
import datetime
import json
import os
import sys
import urllib.parse
import urllib.request

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, RDF, RDFS, SKOS, XSD

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SOURCES = [os.path.join(ROOT, "abox", "library", "crops-gbif.ttl")]
OUT = os.path.join(ROOT, "abox", "library", "taxa-wikidata.ttl")
PERMA = Namespace("https://permaculture.digitalhome.cloud/ontology#")
DWC = Namespace("http://rs.tdwg.org/dwc/terms/")
WD = "http://www.wikidata.org/entity/"
GBIF_SPECIES = "https://www.gbif.org/species/"
TAXREF = "https://taxref.mnhn.fr/taxref-web/taxa/"
ENDPOINT = "https://query.wikidata.org/sparql"
QUERY = """SELECT ?gbif ?item ?taxref ?iucn ?iucnLabel WHERE {
  VALUES ?gbif { %s }
  ?item wdt:P846 ?gbif .
  OPTIONAL { ?item wdt:P3186 ?taxref }
  OPTIONAL { ?item wdt:P141 ?iucn }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}"""


def ask(keys):
    q = QUERY % " ".join(f'"{k}"' for k in keys)
    req = urllib.request.Request(ENDPOINT + "?" + urllib.parse.urlencode({"query": q}),
                                 headers={"Accept": "application/sparql-results+json",
                                          "User-Agent": "permaculture-digitalhome-cloud/0.1 (crop library)"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)["results"]["bindings"]


def link(rows, taxa):
    """rows: SPARQL bindings; taxa: {gbif key: taxon IRI}. Returns (graph, problems)."""
    g = Graph()
    for prefix, ns in (("perma", PERMA), ("dwc", DWC), ("skos", SKOS), ("dcterms", DCTERMS)):
        g.bind(prefix, ns)
    today = Literal(datetime.date.today().isoformat(), datatype=XSD.date)
    found = {}
    for b in rows:
        key = b["gbif"]["value"]
        found.setdefault(key, []).append(b)
    problems = []
    for key, taxon in sorted(taxa.items()):
        items = {b["item"]["value"] for b in found.get(key, [])}
        if len(items) != 1:
            problems.append(f"GBIF {key}: {len(items)} Wikidata items" + (f" ({', '.join(sorted(items))})" if items else ""))
            continue
        item = URIRef(items.pop())
        g.add((taxon, SKOS.exactMatch, item))
        taxref = {b["taxref"]["value"] for b in found[key] if "taxref" in b}
        if len(taxref) == 1:
            t = taxref.pop()
            g.add((taxon, PERMA.taxrefId, Literal(t)))
            g.add((taxon, SKOS.exactMatch, URIRef(TAXREF + t)))
        elif taxref:
            problems.append(f"GBIF {key}: several TAXREF IDs {sorted(taxref)}, none recorded")
        for b in found[key]:
            if "iucn" in b:
                status = URIRef(b["iucn"]["value"])
                g.add((taxon, PERMA.iucnGlobalStatus, status))
                g.add((status, RDFS.label, Literal(b["iucnLabel"]["value"], lang="en")))
        g.add((taxon, DCTERMS.modified, today))
    return g, problems


def main():
    src = Graph()
    for p in SOURCES:
        src.parse(p)
    taxa = {str(t)[len(GBIF_SPECIES):]: t for t in src.subjects(RDF.type, DWC.Taxon) if str(t).startswith(GBIF_SPECIES)}
    g, problems = link(ask(sorted(taxa)), taxa)
    for t in sorted(taxa.values()):
        name = src.value(t, DWC.scientificName)
        print(f"{name:28s} TAXREF {g.value(t, PERMA.taxrefId) or '-':>7s}  "
              f"{str(g.value(t, SKOS.exactMatch) or '-').rsplit('/', 1)[-1] if any(str(o).startswith(WD) for o in g.objects(t, SKOS.exactMatch)) else '-'}  "
              f"IUCN {g.value(g.value(t, PERMA.iucnGlobalStatus), RDFS.label) or '-'}")
    with open(OUT, "w") as fh:
        fh.write("# Generated by packages/ontology/tools/wikidata_link.py from the Wikidata Query Service.\n"
                 "# Do not edit: rerun the tool.\n" + g.serialize(format="turtle"))
    print(f"-> {OUT}")
    for p in problems:
        print(f"NOT LINKED: {p}", file=sys.stderr)
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
