#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""A site file's vegetation layer as an A-Box (perma:VegetationUnit), checked with the SHACL shapes.

    ontology/.venv/bin/python ontology/tools/vegetation_abox.py twin/sites/permademo/site.json OUT.ttl --site-id permademo

Until the cloud holds the site model, the twin's site file is where the
vegetation map is drawn; this turns it into the ontology's terms so the
same map can be validated, synced to the nest and shown in the app.
Exit code 1 when the A-Box does not conform.
"""
import argparse
import json
import os
import sys
from decimal import Decimal

from pyshacl import validate
from rdflib import BNode, Graph, Literal, Namespace
from rdflib.namespace import RDF, RDFS, XSD

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
PERMA = Namespace("https://permaculture.digitalhome.cloud/ontology#")
ID = Namespace("https://permaculture.digitalhome.cloud/id/")
GEO = Namespace("http://www.opengis.net/ont/geosparql#")
DWC = Namespace("http://rs.tdwg.org/dwc/terms/")
CLASS = {"tree": "Tree", "shrub": "Shrub", "hedge": "Hedge", "bramble": "Bramble", "meadow": "Meadow",
         "tall_grass": "TallGrass", "crop": "Crop", "bare_soil": "BareSoil"}
STATUS = {"existing": "Existing", "planted": "Planted", "planned": "Planned"}
MAP = {"to_confirm": "ToConfirm", "confirmed": "Confirmed", "rejected": "Rejected"}


def dec(x):
    return Literal(Decimal(f"{float(x):.2f}"), datatype=XSD.decimal)


def wkt(v):
    if "circle" in v:
        x, y = v["circle"]
        return f"POINT({x:.2f} {y:.2f})"
    ring = v["polygon"] + [v["polygon"][0]]
    return "POLYGON((" + ", ".join(f"{x:.2f} {y:.2f}" for x, y in ring) + "))"


def abox(site, site_id):
    g = Graph()
    g.bind("perma", PERMA)
    g.bind("id", ID)
    g.bind("geo", GEO)
    g.bind("dwc", DWC)
    for v in site.get("vegetation", []):
        u = ID[f"{site_id}-{v['id']}"]
        single = "circle" in v
        g.add((u, RDF.type, PERMA.Plant if single else PERMA.VegetationPatch))
        g.add((u, RDFS.label, Literal(v["id"].replace("_", " "), lang="en")))
        g.add((u, PERMA.vegetationClass, PERMA[CLASS[v["class"]]]))
        g.add((u, PERMA.vegetationStatus, PERMA[STATUS[v.get("status", "existing")]]))
        g.add((u, PERMA.mapStatus, PERMA[MAP[v.get("map_status", "to_confirm")]]))
        if "height_m" in v:
            g.add((u, PERMA.heightM, dec(v["height_m"])))
        if "canopy" in v:
            g.add((u, PERMA.hasCanopy, Literal(bool(v["canopy"]))))
        if "canopy_r" in v:
            g.add((u, PERMA.canopyRadiusM, dec(v["canopy_r"])))
        if "source" in v:
            g.add((u, PERMA.mapSource, Literal(v["source"])))
        if "note" in v:
            g.add((u, RDFS.comment, Literal(v["note"], lang="en")))
        if "species" in v:                       # a name until perma-bio links the GBIF/TAXREF IRI
            g.add((u, DWC.scientificName, Literal(v["species"])))
        geom = BNode()
        g.add((u, GEO.hasGeometry, geom))
        g.add((geom, GEO.asWKT, Literal(wkt(v), datatype=GEO.wktLiteral)))
    return g


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("site")
    ap.add_argument("out")
    ap.add_argument("--site-id", required=True)
    a = ap.parse_args()
    with open(a.site) as fh:
        g = abox(json.load(fh), a.site_id)
    data = Graph()
    data += g
    data.parse(os.path.join(ROOT, "tbox", "perma-vegetation-concepts.ttl"))
    shapes = Graph().parse(os.path.join(ROOT, "shapes", "perma-vegetation-shapes.ttl"))
    ok, _, text = validate(data, shacl_graph=shapes)
    header = (f"# Generated by ontology/tools/vegetation_abox.py from {os.path.basename(os.path.dirname(a.site))}"
              f"/site.json. Do not edit: change the site file and regenerate.\n")
    with open(a.out, "w") as fh:
        fh.write(header + g.serialize(format="turtle"))
    print(f"{len(set(g.subjects(RDF.type, None)))} vegetation units -> {a.out}: "
          f"{'conforms' if ok else 'DOES NOT CONFORM'}")
    if not ok:
        print(text, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
